/* Run with ROUTE_BASE_URL and optional PLAYWRIGHT_MODULE. No npm dependency. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/opt/data/home/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const assert=require('node:assert/strict');
const fixture={disclaimer:'技術說明：'.repeat(80),places:{north:{label:'北部',x:270,y:120},naha:{label:'那霸',x:90,y:420,insetX:120,insetY:100}},days:Array.from({length:5},(_,i)=>({day:i+1,variants:[{id:'main',label:'每日路線',note:'參考行程',stops:[{place:'north',itemIndex:2},{place:'naha',itemIndex:3},{place:null,itemIndex:4,label:'餐廳待確認'}],legs:[{from:0,to:1,minutes:[40,60],source:'https://www.openstreetmap.org/copyright',note:'車程參考'},{from:1,to:2,minutes:null,note:'待確認'}]},...(i===2||i===3?[{id:'alternative',label:i===2?'不參加浮潛':'Outlet 單獨往返',note:'自選，不必全部走完',stops:[{place:'naha',itemIndex:3}],legs:[]}]:[])]}))};
(async()=>{const browser=await chromium.launch({headless:true});try{
 for(const width of [320,390]){const context=await browser.newContext({viewport:{width,height:844},reducedMotion:'reduce',serviceWorkers:'block'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/data/route-map.json',r=>r.fulfill({json:fixture}));await page.goto((process.env.ROUTE_BASE_URL||'http://localhost:8769')+'/?now=2026-10-06T13:00');await page.locator('[data-trip-panel]').waitFor();
 for(let i=0;i<5;i++){await page.locator('.tab').nth(i).click();const map=page.locator('details[data-route-map]');await map.waitFor();assert.equal(await map.count(),1);assert.equal(await map.evaluate(e=>e.open),false);assert.equal(await map.evaluate(e=>e.previousElementSibling.hasAttribute('data-trip-panel')&&e.nextElementSibling.matches('.timeline')),true);await map.locator(':scope > summary').click();assert.equal(await map.locator('[data-route-stop]').count(),5);assert.equal(await map.locator('svg').count(),2);assert.ok((await map.locator('.route-disclaimer').innerText()).length<100);assert.match(await map.locator('.route-legs').innerText(),/北部.*那霸/);assert.equal(await map.locator('.route-inset-label').count(),1);assert.match(await map.innerText(),/40–60/);assert.match(await map.innerText(),/待確認/);assert.equal(await map.locator('[data-route-sources] a').count(),1);assert.match(await map.locator('[data-route-total]').innerText(),/40–60.*1 段/);
 if(i===2||i===3){await map.locator('[data-route-variant]').nth(1).click();assert.equal(await map.locator('[data-route-stop]').count(),2);assert.doesNotMatch(await map.innerText(),/40–60/);}
 const marker=map.locator('.route-marker').first();const box=await marker.boundingBox();assert.ok(box.width>=44&&box.height>=44);const idx=await marker.getAttribute('data-route-stop');await marker.focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.dataset.routeItem),idx);assert.ok(await page.evaluate(()=>document.activeElement.getBoundingClientRect().top>=document.querySelector('.tabbar').getBoundingClientRect().bottom));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await page.locator('.tab').last().click();assert.equal(await page.locator('[data-route-map]').count(),0);assert.deepEqual(errors,[]);await context.close();console.log('PASS lifecycle/options/keyboard/320 or 390:',width);}
 const context=await browser.newContext({serviceWorkers:'block'});const page=await context.newPage();await page.route('**/data/route-map.json',r=>r.fulfill({status:503,body:'Unavailable'}));await page.goto((process.env.ROUTE_BASE_URL||'http://localhost:8769')+'/?now=2026-10-06T13:00');await page.locator('[data-route-map]').waitFor();assert.match(await page.locator('[data-route-map]').innerText(),/暫時無法載入/);assert.ok(await page.locator('.card').count()>0);await context.close();console.log('PASS load failure preserves cards');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
